---
homebrew_packages:
  - awscli
  - bash
  - coreutils
  - fontconfig
  - freetype
  - git
  - glib
  - gnutls
  - gnu-sed
  - jpeg
  - keychain
  - nmap
  - openssh
  - openssl
  - packer
  - python
  - readline
  - shellcheck
  - ssh-copy-id
  - tmux
  - wget

homebrew_casks:
  - amazon-music
  - appcleaner
  - atom
  - flash-player
  - google-drive
  - iterm2
  - macvim
  - remoteviewer
  - rocket-chat
  - sonos
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - xquartz

